### ISSUE TITLE
objects: consider using CamelCase instead of ALL_UPPER for constants

### ISSUE THREAD

**Issue by quasilyte** [gosh-lang/gosh#17]
```diff

// The list of object types.
const (
-	INTEGER Type = iota
-	BOOLEAN
-	STRING
-	FUNCTION
-	GOFUNCTION
-	CONTINUE
+	Integer Type = iota
+	Boolean
+	String
+	Function
+	GoFunction
+	Continue
)
```
It may also require examples/tests update if anything depends on the stringer output for those.

**Comment by AlekSi** [comment]
PRs are welcome!

**Comment by MrYadro** [comment]
I can take it!

**Comment by bombsimon** [comment]
@MrYadro Oh, I was just about to commit a PR so I hope you haven't started yet?

**Comment by MrYadro** [comment]
@bombsimon nah, that's okay you can have it

**Comment by AlekSi** [comment]
@MrYadro There is another simple issue: #19.
